[trait]
description = "SPA-only local admin workspace"
version = "v260326.215336"
checksum = "1eb03200db65a78c5d76ec868203661d6039a1809f08502ec3e98f021a893e47"
author = "system"
tags = ["www", "admin", "spa", "local"]
provides = ["www/webpage"]

[signature]

[signature.returns]
type = "string"
description = "HTML SPA admin workspace"

[implementation]
language = "rust"
source = "builtin"
entry = "spa"
wasm = true