[trait]
description = "SPA-only local admin workspace"
version = "v260328.015103"
checksum = "b7798ac087f2ccbf348d01dc3f69d25ec611f337c1902a1ad166b70ed41bb45e"
author = "system"
tags = ["www", "admin", "spa", "local"]
provides = ["www/webpage"]

[signature]

[signature.returns]
type = "string"
description = "HTML SPA admin workspace"

[implementation]
language = "rust"
source = "builtin"
entry = "spa"
wasm = true