[trait]
description = "In-browser WASM kernel playground"
version = "v260324.131148"
checksum = "f6cabec48068e3e11f5e1c3f3203d53f7e4383606212689c038d7a7a84085332"
author = "system"
tags = ["www", "webpage", "wasm"]
provides = ["www/webpage"]

[signature]

[signature.returns]
type = "string"
description = "HTML page loading the WASM kernel"

[implementation]
language = "rust"
source = "builtin"
entry = "wasm_page"
wasm = true