/**
 * Menyoo Object Spooner XML exporter.
 *
 * Produces XML compatible with Menyoo 1.6+ Object Spooner mod.
 * Format target: Menyoo Spooner "SpoonerPlacements" schema.
 *
 * Notes:
 *  - <Value>  is the Jenkins one-at-a-time hash of the model name (signed 32-bit).
 *  - <Type>   entity type: 3=Prop/Object, 2=Vehicle, 1=Ped.
 *  - Rotation quaternion is stored directly as X/Y/Z/W components.
 *  - FrozenPos=true prevents physics from moving the object on spawn.
 *  - All coordinates are GTA V world-space metres.
 */

import type { SceneDescription, SceneObject, SceneGroup } from '../schema/scene.js';
import { MENYOO_TYPE } from '../schema/scene.js';
import { joaat } from '../engine/transform.js';

// ─── XML Helpers ──────────────────────────────────────────────────────────────

function esc(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function tag(name: string, value: string | number, indent = 0): string {
  const pad = '  '.repeat(indent);
  return `${pad}<${name}>${value}</${name}>`;
}

function tagf(name: string, value: number, indent = 0, decimals = 6): string {
  return tag(name, value.toFixed(decimals), indent);
}

function vec3Tag(name: string, x: number, y: number, z: number, indent: number): string {
  const pad = '  '.repeat(indent);
  return [
    `${pad}<${name}>`,
    tagf('X', x, indent + 1),
    tagf('Y', y, indent + 1),
    tagf('Z', z, indent + 1),
    `${pad}</${name}>`,
  ].join('\n');
}

function quatTag(name: string, x: number, y: number, z: number, w: number, indent: number): string {
  const pad = '  '.repeat(indent);
  return [
    `${pad}<${name}>`,
    tagf('X', x, indent + 1),
    tagf('Y', y, indent + 1),
    tagf('Z', z, indent + 1),
    tagf('W', w, indent + 1),
    `${pad}</${name}>`,
  ].join('\n');
}

// ─── Entity Serialisation ─────────────────────────────────────────────────────

function serializeEntity(obj: SceneObject, indent = 2): string {
  const pad = '  '.repeat(indent);
  const hash = joaat(obj.model);
  const entityType = MENYOO_TYPE[obj.type] ?? 3;

  const lines: string[] = [
    `${pad}<SpoonerEntity>`,
    tag('Type', entityType, indent + 1),
    tag('Value', hash, indent + 1),
    vec3Tag('Position',
      obj.position.x, obj.position.y, obj.position.z, indent + 1),
    quatTag('Rotation',
      obj.rotation.x, obj.rotation.y, obj.rotation.z, obj.rotation.w, indent + 1),
    // Zero velocity — objects are frozen
    vec3Tag('Velocity', 0, 0, 0, indent + 1),
    vec3Tag('AngularVelocity', 0, 0, 0, indent + 1),
    tag('Health', obj.health, indent + 1),
    tag('Armor', 0, indent + 1),
    tag('LODDistance', obj.lodDistance, indent + 1),
    tag('TextureVariation', obj.textureVariation, indent + 1),
    tag('OpacityLevel', 255, indent + 1),
    tag('FrozenPos', obj.frozen ? 'true' : 'false', indent + 1),
    tag('Dynamic', obj.dynamic ? 'true' : 'false', indent + 1),
    tag('InitialHandle', -1, indent + 1),
    `${pad}</SpoonerEntity>`,
  ];
  return lines.join('\n');
}

// ─── Group Serialisation (Menyoo Collection) ──────────────────────────────────

function serializeGroupComment(group: SceneGroup, indent = 2): string {
  const pad = '  '.repeat(indent);
  return `${pad}<!-- Group: ${esc(group.name)} (${group.objectIds.length} objects) -->`;
}

// ─── Top-Level Export ─────────────────────────────────────────────────────────

export interface MenyooExportOptions {
  /** Include XML comment header with generation metadata */
  includeHeader?: boolean;
  /** Include group comments before each group's entities */
  includeGroupComments?: boolean;
  /** Indent the XML output */
  prettyPrint?: boolean;
}

export function exportMenyooXML(
  scene: SceneDescription,
  opts: MenyooExportOptions = {},
): string {
  const {
    includeHeader = true,
    includeGroupComments = true,
    prettyPrint = true,
  } = opts;

  // Build object-ID → group map for comment placement
  const objectGroup = new Map<string, SceneGroup>();
  for (const group of scene.groups) {
    for (const id of group.objectIds) {
      objectGroup.set(id, group);
    }
  }

  const lines: string[] = [];

  // XML declaration
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');

  if (includeHeader) {
    lines.push('<!--');
    lines.push(`  Generated by gta-builder v${scene.metadata.generatorVersion}`);
    lines.push(`  Title:   ${esc(scene.metadata.title)}`);
    lines.push(`  Seed:    ${scene.metadata.seed}`);
    lines.push(`  Date:    ${scene.metadata.generatedAt}`);
    lines.push(`  Objects: ${scene.objects.length}`);
    lines.push(`  Groups:  ${scene.groups.length}`);
    if (scene.metadata.prompt) {
      lines.push(`  Prompt:  ${esc(scene.metadata.prompt)}`);
    }
    lines.push('-->');
  }

  lines.push('<SpoonerPlacements>');
  lines.push('  <SpawnPlayer>false</SpawnPlayer>');
  const sp = scene.params.startPosition;
  lines.push('  <ReferenceCoords>');
  lines.push(tagf('X', sp.x, 2));
  lines.push(tagf('Y', sp.y, 2));
  lines.push(tagf('Z', sp.z, 2));
  lines.push('  </ReferenceCoords>');
  lines.push('  <IPLs />');
  lines.push('  <Entities>');

  if (includeGroupComments) {
    // Emit entities in group order, with group comment headers
    const emittedIds = new Set<string>();

    for (const group of scene.groups) {
      if (group.objectIds.length === 0) continue;

      lines.push(serializeGroupComment(group, 2));

      for (const id of group.objectIds) {
        const obj = scene.objects.find((o) => o.id === id);
        if (!obj) continue;
        lines.push(serializeEntity(obj, 2));
        emittedIds.add(id);
      }
    }

    // Emit any orphan objects not in a group
    for (const obj of scene.objects) {
      if (!emittedIds.has(obj.id)) {
        lines.push(serializeEntity(obj, 2));
      }
    }
  } else {
    for (const obj of scene.objects) {
      lines.push(serializeEntity(obj, 2));
    }
  }

  lines.push('  </Entities>');
  lines.push('</SpoonerPlacements>');

  return lines.join('\n') + '\n';
}

// ─── Patch: inject ReferenceCoords into existing XML if missing ───────────────

/**
 * Given a Menyoo SpoonerPlacements XML string, ensures a <ReferenceCoords>
 * block is present immediately after <SpawnPlayer>.
 *
 * Heuristic for coords when none exist:
 *   Take the X/Y/Z from the first <Position> block in the file
 *   (i.e. the first entity's world position, which is always the track start).
 *
 * Returns the (possibly modified) XML string, unchanged if already patched.
 */
export function injectReferenceCoords(xml: string): string {
  // Already has it — nothing to do
  if (/<ReferenceCoords>/i.test(xml)) return xml;

  // Extract coords from the first <Position> block
  const posMatch = xml.match(
    /<Position>\s*<X>([-\d.]+)<\/X>\s*<Y>([-\d.]+)<\/Y>\s*<Z>([-\d.]+)<\/Z>\s*<\/Position>/i,
  );
  if (!posMatch) return xml; // can't determine coords — leave unchanged

  const [, x, y, z] = posMatch;
  const block = [
    '  <ReferenceCoords>',
    `    <X>${x}</X>`,
    `    <Y>${y}</Y>`,
    `    <Z>${z}</Z>`,
    '  </ReferenceCoords>',
  ].join('\n');

  // Insert after <SpawnPlayer>...</SpawnPlayer>
  return xml.replace(/(<SpawnPlayer>[^<]*<\/SpawnPlayer>)/, `$1\n${block}`);
}

// ─── Convenience: Scene → JSON ────────────────────────────────────────────────

export function exportSceneJSON(scene: SceneDescription): string {
  return JSON.stringify(scene, null, 2);
}

// ─── Stat Summary ─────────────────────────────────────────────────────────────

export interface ExportStats {
  entityCount: number;
  props: number;
  vehicles: number;
  peds: number;
  groups: number;
  xmlBytes: number;
}

export function getExportStats(scene: SceneDescription, xml: string): ExportStats {
  return {
    entityCount: scene.objects.length,
    props:    scene.objects.filter((o) => o.type === 'prop').length,
    vehicles: scene.objects.filter((o) => o.type === 'vehicle').length,
    peds:     scene.objects.filter((o) => o.type === 'ped').length,
    groups:   scene.groups.length,
    xmlBytes: Buffer.byteLength(xml, 'utf8'),
  };
}
