package traits:sys-list@0.1.0;

interface %list {
  %list: func(namespace: option<string>) -> result<list<string>, string>;
}

world list-world {
  import traits:kernel-host/dispatch@0.1.0;
  export %list;
}

