// ── Auto-generated WASM trait modules, dispatch, and constants ──
// Generated by wasm/build.rs from .trait.toml files with wasm = true.
// Do not edit manually — add wasm = true to a .trait.toml instead.
include!(concat!(env!("OUT_DIR"), "/wasm_compiled_traits.rs"));
