name = "traits-relay"
main = "src/index.js"
compatibility_date = "2024-09-23"
workers_dev = true

routes = [
  { pattern = "relay.traits.build", custom_domain = true }
]

[durable_objects]
bindings = [{ name = "RELAY", class_name = "RelaySession" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelaySession"]
