// bridge.c — wit-bindgen-c export glue for the Scheme hello example.
//
// Build (handled by ../build.sh):
//   1. wit-bindgen c --world hello-world --out-dir . ./wit
//   2. Generate init_scm.h and hello_scm.h from init.scm / hello.scm.
//   3. $WASI_SDK/bin/clang -mexec-model=reactor -O2 \
//        -DSTANDALONE=0 -DUSE_DL=0 -DUSE_INTERFACE=1 \
//        -I. bridge.c scheme.c hello_world.c hello_world_component_type.o \
//        -o hello-scheme.module.wasm
//   4. wasm-tools component new ... -o hello-scheme.component.wasm

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "scheme.h"
#include "scheme-private.h"
#include "hello_world.h"

// Embedded TinyScheme init.scm and our hello.scm (generated by build.sh).
#include "init_scm.h"
#include "hello_scm.h"

// Capture the value passed to (capture-result ...) so we can ship it back
// through the WIT export.
static char *g_captured = NULL;
static size_t g_captured_len = 0;

static pointer capture_result(scheme *sc, pointer args) {
    if (args == sc->NIL) return sc->NIL;
    pointer v = sc->vptr->pair_car(args);
    if (!sc->vptr->is_string(v)) return sc->NIL;
    char *s = sc->vptr->string_value(v);
    size_t n = strlen(s);
    free(g_captured);
    g_captured = (char *)malloc(n);
    if (g_captured) {
        memcpy(g_captured, s, n);
        g_captured_len = n;
    } else {
        g_captured_len = 0;
    }
    return sc->NIL;
}

// Helper: append into a heap buffer.
static void append(char **buf, size_t *len, size_t *cap, const char *s, size_t n) {
    if (*len + n > *cap) {
        size_t new_cap = (*cap ? *cap * 2 : 128);
        while (new_cap < *len + n) new_cap *= 2;
        *buf = (char *)realloc(*buf, new_cap);
        *cap = new_cap;
    }
    memcpy(*buf + *len, s, n);
    *len += n;
}

// Build "(capture-result (hello \"<escaped-name>\"))" as a heap string.
static char *build_call(const uint8_t *name, size_t name_len) {
    char *buf = NULL;
    size_t len = 0, cap = 0;
    static const char prefix[] = "(capture-result (hello \"";
    static const char suffix[] = "\"))";
    append(&buf, &len, &cap, prefix, sizeof(prefix) - 1);
    for (size_t i = 0; i < name_len; i++) {
        char c = (char)name[i];
        if (c == '\\' || c == '"') {
            append(&buf, &len, &cap, "\\", 1);
        }
        append(&buf, &len, &cap, &c, 1);
    }
    append(&buf, &len, &cap, suffix, sizeof(suffix) - 1);
    append(&buf, &len, &cap, "", 1); // NUL terminate
    return buf;
}

bool exports_hello_scheme_hello_hello(hello_world_string_t *name,
                                      hello_world_string_t *ret,
                                      hello_world_string_t *err) {
    (void)err;

    scheme *sc = scheme_init_new();
    if (!sc) return false;

    // No file I/O needed; route any (display ...) to /dev/null-equivalent
    // by giving the interpreter a dummy string output port.
    static char devnull[1];
    scheme_set_output_port_string(sc, devnull, devnull + sizeof(devnull));

    // Bootstrap stdlib.
    scheme_load_string(sc, (const char *)init_scm);

    // Install (capture-result <string>) foreign function so we can extract
    // the result of (hello name) without parsing scheme output.
    sc->vptr->scheme_define(
        sc, sc->global_env,
        sc->vptr->mk_symbol(sc, "capture-result"),
        sc->vptr->mk_foreign_func(sc, capture_result));

    // Define (hello name).
    scheme_load_string(sc, (const char *)hello_scm);

    // Call it.
    g_captured = NULL;
    g_captured_len = 0;
    char *call = build_call(name->ptr, name->len);
    if (!call) {
        scheme_deinit(sc);
        free(sc);
        return false;
    }
    scheme_load_string(sc, call);
    free(call);

    bool ok = (g_captured != NULL && g_captured_len > 0);
    if (ok) {
        ret->ptr = (uint8_t *)g_captured;
        ret->len = g_captured_len;
        g_captured = NULL; // ownership transferred to caller
        g_captured_len = 0;
    }

    scheme_deinit(sc);
    free(sc);
    return ok;
}
