package traits:kernel-call@0.1.0;

interface call {
  call: func(trait-path: string, args: option<list<string>>) -> result<string, string>;
}

world call-world {
  import traits:kernel-host/dispatch@0.1.0;
  export call;
}
